language: generic
matrix:
  include: 
    - os: osx
      osx_image: xcode10.2
      env:
        - CACHE_NAME=SWIFT5_0
        - SWIFT_VERSION=5.0
        - IOS_SIMULATOR='name=iPhone 6s,OS=12.2'
        - IOS_SDK=iphonesimulator12.2
        - TVOS_SIMULATOR='name=Apple TV 4K (at 1080p)'
        - TVOS_SDK=appletvsimulator12.2
        - WATCHOS_SIMULATOR='name=Apple Watch Series 4 - 44mm'
        - WATCHOS_SDK=watchsimulator5.2
    - os: osx
      osx_image: xcode10.1
      env:
        - CACHE_NAME=SWIFT4_2
        - SWIFT_VERSION=4.2
        - IOS_SIMULATOR='name=iPhone 6s,OS=12.1'
        - IOS_SDK=iphonesimulator12.1
        - TVOS_SIMULATOR='name=Apple TV 4K (at 1080p)'
        - TVOS_SDK=appletvsimulator12.1
        - WATCHOS_SIMULATOR='name=Apple Watch - 42mm'
        - WATCHOS_SDK=watchsimulator5.1        
    - os: osx
      osx_image: xcode9.4
      env: 
        - CACHE_NAME=SWIFT4_1
        - SWIFT_VERSION=4.0 # it's in fact 4.1
        - IOS_SIMULATOR='name=iPhone 6s,OS=11.4'
        - IOS_SDK=iphonesimulator11.4
        - TVOS_SIMULATOR='name=Apple TV 4K (at 1080p)'
        - TVOS_SDK=appletvsimulator11.4
        - WATCHOS_SIMULATOR='name=Apple Watch - 42mm'
        - WATCHOS_SDK=watchsimulator4.3  

notifications:
  email: false

cache:
  edge: true
  directories:
    - Carthage
    - .build

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=SwiftyUserDefaults.xcodeproj

before_install:
  - gem install cocoapods -v 1.6.0
  - gem install xcpretty
  - brew install xcodegen
  # - npm install -g danger
  # - brew install danger/tap/danger-swift

script:
  - set -o pipefail
  - if [[ "$SWIFT_VERSION" == "5.0" ]]; then mv Cartfile_5.0.private Cartfile.private; fi
  - if [[ "$SWIFT_VERSION" == "5.0" ]]; then mv Cartfile_5.0.resolved Cartfile.resolved; fi
  - if [[ "$SWIFT_VERSION" == "5.0" ]]; then mv Package_5.0.swift Package.swift; fi
  - if [[ "$SWIFT_VERSION" == "5.0" ]]; then mv Package_5.0.resolved Package.resolved; fi
  - carthage update --no-use-binaries --cache-builds --verbose
  - xcodebuild -version
  - xcodebuild -showsdks
  
  - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults' -sdk $IOS_SDK  -destination "$IOS_SIMULATOR" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO SWIFT_VERSION=$SWIFT_VERSION build | xcpretty
  - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults' -sdk $TVOS_SDK -destination "$TVOS_SIMULATOR" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO SWIFT_VERSION=$SWIFT_VERSION build | xcpretty
  - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults' -sdk $WATCHOS_SDK -destination "$WATCHOS_SIMULATOR" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO SWIFT_VERSION=$SWIFT_VERSION build | xcpretty
  - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty
  
  # - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults' -sdk $IOS_SDK  -destination "$IOS_SIMULATOR" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO SWIFT_VERSION=$SWIFT_VERSION test | xcpretty
  # - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults' -sdk $TVOS_SDK -destination "$TVOS_SIMULATOR" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO SWIFT_VERSION=$SWIFT_VERSION test | xcpretty
  # - xcodebuild -project "$PROJECT" -scheme 'SwiftyUserDefaults' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty
  
  - swift build
  - swift test
  - pod lib lint

  - mkdir TestCocoaPods && cd TestCocoaPods && echo "name: TestCocoaPods\ntargets:\n  TestCocoaPods:\n    type: application\n    platform: iOS\n    deploymentTarget: '11.0'" > project.yml && xcodegen generate && echo "target 'TestCocoaPods' do\n   use_frameworks\!\n  pod 'SwiftyUserDefaults', :path => '../'\nend" > Podfile && pod install && cd ../;
  # there is a problem with danger-swift currently, commenting it for now
  # - DEBUG="*" danger process danger-swift